version: '3'
services:
  read-around:
    build: .
    restart: on-failure
    container_name: ECGPTvBeta1.0
    read_only: false
    ports:
      - 8010:8010
    deploy:
      resources:
        limits:
          cpus: "1.0"
