version: '3'
services:
  challenge:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "31080:80"
    restart: always
    environment:
      FLAG: "TCP1P{Well, I am just an average CTF player in the face of international CTF. It should be the easiest challenge in 0CTF 2023, though.}"
