version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - 10994:8080
    environment:
      - DATASRC=${DB_USER}:${DB_PASS}@tcp(mydb:3306)/${DB_NAME}
    depends_on:
      - mydb
  mydb:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
