version: "3"

services:
  app:
    build: .
    ports:
      - 63459:8000
    networks:
      - no_internet
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"

networks:
  no_internet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
