name: paradigm-ctf-challenge
services:
  launcher:
    image: challenge
    build:
      context: .
    ports:
      - "${PUBLIC_PORT}:8080"
    environment:
      - CHALLENGE_ID=${CHALLENGE_ID}
      - PUBLIC_IP=${PUBLIC_HOST}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - FLAG=${FLAG}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - ENV=production
